name: asgm1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  shared_preferences: ^2.5.3
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  intl: ^0.18.1
  
  percent_indicator: ^4.2.2

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/Profile.png
   - assets/images/courses/Yoga.png
   - assets/images/courses/Cardio.png
   - assets/images/courses/Home-Gym.jpg
   - assets/images/courses/Pilates.jpg
   - assets/images/courses/Kickboxing.jpg
   - assets/images/courses/HIIT.jpg
   - assets/images/promotion/50%.jpg
   - assets/images/promotion/member.png
   - assets/images/promotion/premium.jpg
   - assets/images/25%.png
   - assets/images/myprofile/people.jpg
   - assets/images/myprofile/membercard.jpg
   - assets/images/myprofile/barcode2.jpg
   - assets/images/myprofile/voucher1.jpg 
   - assets/images/myprofile/voucher2.jpg     
   - assets/images/myprofile/voucher3.jpg   
   - assets/images/food/breakfast.jpg
   - assets/images/food/lunch.jpg  
   - assets/images/food/dinner.jpg  
   - assets/images/food/snack.jpg 
   - assets/images/myprofile/qrcode.png
   - assets/images/footsteps.png
   - assets/images/heartbeat.png
   - assets/images/calorieschart.png
   - assets/images/pic1.jpg
   - assets/images/pic2.jpg
   - assets/images/pic3.jpg
   - assets/images/pic4.jpg
   - assets/images/pic5.jpg
   - assets/images/pic6.jpg
   - assets/images/post_pic1.jpg
   - assets/images/post_pic2.jpg    
   - assets/images/exercise/pushup.png   
   - assets/images/exercise/situp.png
   - assets/images/exercise/jumpingjacks.png
   - assets/images/exercise/plank.png
   - assets/images/exercise/squats.png
   - assets/images/exercise/lunges.png
   - assets/images/exercise/mountainclimbers.png
   - assets/images/exercise/highknees.png
   - assets/images/exercise/run.png
   - assets/images/exercise/swim.png
   - assets/images/exercise/rowing.png
   - assets/images/exercise/cycling.png
   - assets/images/analyticschart.png
   - assets/images/courses/BodyBalance.jpg
   - assets/images/courses/BodyCombat.jpg
   - assets/images/courses/Boxing.jpg
   - assets/images/trainers/Trainer1.jpg
   - assets/images/trainers/Trainer2.jpg
   - assets/images/trainers/Trainer3.jpg
   - assets/images/trainers/Trainer4.jpg
   - assets/images/trainers/Trainer5.jpg
   - assets/images/trainers/Trainer6.jpg
   - assets/images/trainers/Trainer7.jpg
   - assets/images/blood_pressure_chart.png
   - assets/images/noprofile.png
   - assets/images/boostifylogo.png
   - assets/images/storypic1.jpeg
   - assets/images/services/fitnessassessment.jpg
   - assets/images/services/groupfitness.jpg
   - assets/images/services/nutritionconsult.jpg
   - assets/images/services/personaltraining.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
