// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtOTpeREhEXw1G081BJp8LTSDwVH8E-w4',
    appId: '1:166630487738:web:7efff7cb59ed5f8c1c3483',
    messagingSenderId: '166630487738',
    projectId: 'mobile-assign-55561',
    authDomain: 'mobile-assign-55561.firebaseapp.com',
    storageBucket: 'mobile-assign-55561.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtOTpeREhEXw1G081BJp8LTSDwVH8E-w4',
    appId: '1:166630487738:android:7efff7cb59ed5f8c1c3483',
    messagingSenderId: '166630487738',
    projectId: 'mobile-assign-55561',
    storageBucket: 'mobile-assign-55561.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtOTpeREhEXw1G081BJp8LTSDwVH8E-w4',
    appId: '1:166630487738:ios:7efff7cb59ed5f8c1c3483',
    messagingSenderId: '166630487738',
    projectId: 'mobile-assign-55561',
    storageBucket: 'mobile-assign-55561.firebasestorage.app',
    iosClientId: '166630487738-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.asgm1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtOTpeREhEXw1G081BJp8LTSDwVH8E-w4',
    appId: '1:166630487738:ios:7efff7cb59ed5f8c1c3483',
    messagingSenderId: '166630487738',
    projectId: 'mobile-assign-55561',
    storageBucket: 'mobile-assign-55561.firebasestorage.app',
    iosClientId: '166630487738-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.asgm1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtOTpeREhEXw1G081BJp8LTSDwVH8E-w4',
    appId: '1:166630487738:windows:7efff7cb59ed5f8c1c3483',
    messagingSenderId: '166630487738',
    projectId: 'mobile-assign-55561',
    authDomain: 'mobile-assign-55561.firebaseapp.com',
    storageBucket: 'mobile-assign-55561.firebasestorage.app',
  );
} 